### ISSUE TITLE
Compatible with Umbraco 8?

### ISSUE THREAD

**Issue by emaad** [vokseverk/Vokseverk.ImageHotspot#10]
Hi,

I am very impressed with the way you implemented such a great control. I just want to know if you planning to make it compatible with Umbraco 8?
Also can you please provide Umbraco Zip for installation.

Thanks

**Comment by greystate** [comment]
Hi @emaad - thank you very much for the praise :)

Yes, I am planning to try my hands at creating a v8 compatible version - but I currently have no ETA on that, as I've not even tried implementing a v8 Property Editor, sorry.

There is ZIP for installation on the releases page here: https://github.com/vokseverk/Vokseverk.ImageHotspot/releases/tag/v0.3

(That is the latest working version that I've used myself — the later ones have a bug in the calculation of the height, sadly)

**Comment by AndersBrohus** [comment]
Any update on this? :)
It works awesome on v7 but i would like to use it for a map on v8 :)

**Comment by greystate** [comment]
Hi @AndersBrohus 

I haven't done anything with this lately, and haven't had the need to use it on a v8 project.

Have you tried installing it on v8? (Just to know how hard it breaks 😁) 

Was pondering putting this up for anyone wanting to grab themselves a Hacktoberfest-challenge :)

**Comment by greystate** [comment]
Hi @emaad & @AndersBrohus — I've just (finally) released a version compatible with Umbraco 8 (as well as v7); There's a ZIP + PropertyValueConverter(s) on the [release page](https://github.com/vokseverk/Vokseverk.ImageHotspot/releases/tag/v1.0.0) if you want to check it out 😀

**Comment by greystate** [comment]
Closed as of v1.0
