### ISSUE TITLE
Not an issue a question...

### ISSUE THREAD

**Issue by benehudson** [vokseverk/Vokseverk.ImageHotspot#12]
Does ImageHotspot support multiple hotspots on one image?

**Comment by greystate** [comment]
Hi @benehudson 

You can't put multiple hotspots on the same property - but this is how we've used it:

- A Document Type has a `mainImage` property (MediaPicker)
- Another property on that doctype has a `hotspots` (or `locations`) property which is a BlockList editor, set up with an Element Type that has a `position` property (ImageHotspot) and maybe other properties related to that location (e.g. `description` or `productsSoldHere` maybe?)

This way the hotspot can have other data associated with it.

Here's a quick demo image:

<img width="1125" alt="ImageHotspotDemo" src="https://user-images.githubusercontent.com/5463/113971228-aa702980-9838-11eb-8a33-5b6c98c405ed.png">

Hope that clears things up!

/Chriztian
